/*
 *  This file is part of paikka.
 *
 *  Paikka is free software: you can redistribute it and/or
 *  modify it under the terms of the GNU Affero General Public License
 *  as published by the Free Software Foundation, either version 3 or
 *  any later version.
 *
 *  Paikka is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied
 *  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with Paikka. If not, see <https://www.gnu.org/licenses/>.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.dedicatedcode.paikka.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Boundary extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Boundary getRootAsBoundary(ByteBuffer _bb) { return getRootAsBoundary(_bb, new Boundary()); }
  public static Boundary getRootAsBoundary(ByteBuffer _bb, Boundary obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Boundary __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long osmId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int level() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String name() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public double minX() { int o = __offset(10); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double minY() { int o = __offset(12); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double maxX() { int o = __offset(14); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double maxY() { int o = __offset(16); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double mirMinX() { int o = __offset(18); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double mirMinY() { int o = __offset(20); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double mirMaxX() { int o = __offset(22); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double mirMaxY() { int o = __offset(24); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public com.dedicatedcode.paikka.flatbuffers.Geometry geometry() { return geometry(new com.dedicatedcode.paikka.flatbuffers.Geometry()); }
  public com.dedicatedcode.paikka.flatbuffers.Geometry geometry(com.dedicatedcode.paikka.flatbuffers.Geometry obj) { int o = __offset(26); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createBoundary(FlatBufferBuilder builder,
      long osmId,
      int level,
      int nameOffset,
      double minX,
      double minY,
      double maxX,
      double maxY,
      double mirMinX,
      double mirMinY,
      double mirMaxX,
      double mirMaxY,
      int geometryOffset) {
    builder.startTable(12);
    Boundary.addMirMaxY(builder, mirMaxY);
    Boundary.addMirMaxX(builder, mirMaxX);
    Boundary.addMirMinY(builder, mirMinY);
    Boundary.addMirMinX(builder, mirMinX);
    Boundary.addMaxY(builder, maxY);
    Boundary.addMaxX(builder, maxX);
    Boundary.addMinY(builder, minY);
    Boundary.addMinX(builder, minX);
    Boundary.addOsmId(builder, osmId);
    Boundary.addGeometry(builder, geometryOffset);
    Boundary.addName(builder, nameOffset);
    Boundary.addLevel(builder, level);
    return Boundary.endBoundary(builder);
  }

  public static void startBoundary(FlatBufferBuilder builder) { builder.startTable(12); }
  public static void addOsmId(FlatBufferBuilder builder, long osmId) { builder.addLong(0, osmId, 0L); }
  public static void addLevel(FlatBufferBuilder builder, int level) { builder.addInt(1, level, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(2, nameOffset, 0); }
  public static void addMinX(FlatBufferBuilder builder, double minX) { builder.addDouble(3, minX, 0.0); }
  public static void addMinY(FlatBufferBuilder builder, double minY) { builder.addDouble(4, minY, 0.0); }
  public static void addMaxX(FlatBufferBuilder builder, double maxX) { builder.addDouble(5, maxX, 0.0); }
  public static void addMaxY(FlatBufferBuilder builder, double maxY) { builder.addDouble(6, maxY, 0.0); }
  public static void addMirMinX(FlatBufferBuilder builder, double mirMinX) { builder.addDouble(7, mirMinX, 0.0); }
  public static void addMirMinY(FlatBufferBuilder builder, double mirMinY) { builder.addDouble(8, mirMinY, 0.0); }
  public static void addMirMaxX(FlatBufferBuilder builder, double mirMaxX) { builder.addDouble(9, mirMaxX, 0.0); }
  public static void addMirMaxY(FlatBufferBuilder builder, double mirMaxY) { builder.addDouble(10, mirMaxY, 0.0); }
  public static void addGeometry(FlatBufferBuilder builder, int geometryOffset) { builder.addOffset(11, geometryOffset, 0); }
  public static int endBoundary(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishBoundaryBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedBoundaryBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Boundary get(int j) { return get(new Boundary(), j); }
    public Boundary get(Boundary obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

