// automatically generated by the FlatBuffers compiler, do not modify

package com.dedicatedcode.paikka.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BuildingList extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static BuildingList getRootAsBuildingList(ByteBuffer _bb) { return getRootAsBuildingList(_bb, new BuildingList()); }
  public static BuildingList getRootAsBuildingList(ByteBuffer _bb, BuildingList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BuildingList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.dedicatedcode.paikka.flatbuffers.Building buildings(int j) { return buildings(new com.dedicatedcode.paikka.flatbuffers.Building(), j); }
  public com.dedicatedcode.paikka.flatbuffers.Building buildings(com.dedicatedcode.paikka.flatbuffers.Building obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int buildingsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public com.dedicatedcode.paikka.flatbuffers.Building.Vector buildingsVector() { return buildingsVector(new com.dedicatedcode.paikka.flatbuffers.Building.Vector()); }
  public com.dedicatedcode.paikka.flatbuffers.Building.Vector buildingsVector(com.dedicatedcode.paikka.flatbuffers.Building.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createBuildingList(FlatBufferBuilder builder,
      int buildingsOffset) {
    builder.startTable(1);
    BuildingList.addBuildings(builder, buildingsOffset);
    return BuildingList.endBuildingList(builder);
  }

  public static void startBuildingList(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addBuildings(FlatBufferBuilder builder, int buildingsOffset) { builder.addOffset(0, buildingsOffset, 0); }
  public static int createBuildingsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startBuildingsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endBuildingList(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishBuildingListBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedBuildingListBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BuildingList get(int j) { return get(new BuildingList(), j); }
    public BuildingList get(BuildingList obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

