/*
 *  This file is part of paikka.
 *
 *  Paikka is free software: you can redistribute it and/or
 *  modify it under the terms of the GNU Affero General Public License
 *  as published by the Free Software Foundation, either version 3 or
 *  any later version.
 *
 *  Paikka is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied
 *  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with Paikka. If not, see <https://www.gnu.org/licenses/>.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.dedicatedcode.paikka.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Name extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Name getRootAsName(ByteBuffer _bb) { return getRootAsName(_bb, new Name()); }
  public static Name getRootAsName(ByteBuffer _bb, Name obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Name __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String lang() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer langAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer langInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String text() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer textInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createName(FlatBufferBuilder builder,
      int langOffset,
      int textOffset) {
    builder.startTable(2);
    Name.addText(builder, textOffset);
    Name.addLang(builder, langOffset);
    return Name.endName(builder);
  }

  public static void startName(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addLang(FlatBufferBuilder builder, int langOffset) { builder.addOffset(0, langOffset, 0); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(1, textOffset, 0); }
  public static int endName(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Name get(int j) { return get(new Name(), j); }
    public Name get(Name obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

